ALTER TABLE /*_*/mt_save_set
  MODIFY mt_set_id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  DROP COLUMN mt_set_time,
  MODIFY mt_set_page_id INT UNSIGNED NOT NULL,
  MODIFY mt_set_subset VARCHAR(50) NOT NULL,
  MODIFY mt_set_rev_id INT UNSIGNED NOT NULL;